### ISSUE TITLE
[Equipe 02] - Levantamento de Requisitos (Fernanda)

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#12]
Reunião com interessados para o Levantamento de Requisitos.
Dia: 22/08/2017
Horário: 19:00Hrs

**Comment by ripkepiccoli** [comment]
Aplicativo de análise sensorial de cerveja
Objetivo:criação de um aplicativo mobile para web com intuito de auxiliar em um evento de cerveja com a análise sensorial, segundo o guia BJBC. O Usuário deve visualizar o guia resumidamente para ver as características de cada cerveja, como amargor,nível de álcool,etc... 
requisitos funcionais e não funcionais:
-Redirecionar o guia para a opção especifica que o usuário escolher.
-Interface simples e amigável.
-Opção de anotar se tomou ou não tomou a cerveja.
-Opção de 5 estrelas/Avaliação.
-Primeira tela/login.
-Segunda tela mostrar os estilos de cervejas disponíveis para o usuário.
-Após selecionar aparecer uma tela com cor, percentual alcoólico,tipo espuma,amargor...
