### ISSUE TITLE
[Equipe 02] - Levantamento de Requisitos (Luis)

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#13]
Reunião com interessados para o Levantamento de Requisitos.
Dia: 22/08/2017
Horário: 19:00Hrs

**Comment by Luisczar15** [comment]
- Analise sensorial.

-  Objetivo : utilizar em eventos.

- Visualizar estilos e verificar cada estilo, de acordo com o guia BJCP.

- Guia BJCP, utilizado para julgar eventos.

- Visualizar o guia , de acordo com o estilo, inicialmente um resumo, quando selecionado para 'ver mais', demonstra o guia todo(daquele estilo).

- Interface amigável.

- Classificação do estilo no máximo 5 estrelas.

- Comentário sobre estilo e sobre evento.

- Avaliação do estilo "Bebi" e "Não bebi".

- Apenas cervejas do evento

- Login pelo Facebook ou algo de gênero.

- Características do estilo: cor, porcentagem alcoólica, tipo de espuma, aroma, índice de amargor.
- Exemplos comerciais.
