### ISSUE TITLE
[Equipe 02] - Descrição de Requisito: - Exemplo Comercial (Frasnelli)

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#26]
Descrição dos seguintes requisitos:
-> Exemplos comerciais

**Comment by frasnellicristian** [comment]
Exemplos Comerciais: O usuário irá escolher um estilo de cerveja que lhe interesse, após a seleção de um estilo os exemplos comerciais serão apresentados ao usuário,
esse exemplos serão derivados do estilo que o mesmo selecionou.

Índice de Amargor: Será informado ao usuário sobre o amargor da cerveja no momento em que é apresentado o estilo da mesma.
