### ISSUE TITLE
[Equipe 02] - Descrição de Requisito Campo para comentário do Usuário (Diayne)

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#27]
Descrição dos seguintes requisitos:
-> Campo para comentário do usuário

**Comment by Diayne** [comment]
- Campo para comentário do usuário: Desenvolver um campo, onde o usuário poderá expressar sua opinião sobre o tipo de cerveja que provou;
- Característica de estilo em evidência ao abrir o estilo (Cor,teor alcoólico, Tipo de espuma): Em cada estilo de cerveja que o usuário selecionar, deverá ter como evidência, as principais características do estilo selecionado, que seria, a cor que a cerveja deve ter, o teor alcoólico, e o tipo de espuma;
