### ISSUE TITLE
[Equipe 02] - Documentação de Requisitos

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#3]
Fazer documentação dos requisitos.
Requisitos Funcionais;
Requisitos Não-Funcionais;
Deem uma olhada: 
https://www.profissionaisti.com.br/2011/06/levantamento-de-requisitos-voce-sabe-o-que-e/

**Comment by gabrielbenedet** [comment]
A análise e especificação de requisitos de software envolve as atividades de determinar os objetivos de um software e as restrições associadas a ele. Ela deve também estabelecer o relacionamento entre estes objetivos e restrições e a especificação precisa do software.

**Comment by gabrielbenedet** [comment]
Seria criar um padrão (ex: não escrever em notepad, outro em word, outro em ppt). 
Pesquisar por: Modelos de documentos de requisitos. 

Tipo uma norma ABNT, mas para o nosso trabalho. 
Ex: Fonte, espaçamentos, etc.

**Comment by Diayne** [comment]
[Documentação de Requisitos Equipe 02.pdf](https://github.com/macielgoettms/ES2017/files/1243590/Documentacao.de.Requisitos.Equipe.02.pdf)
