### ISSUE TITLE
[Equipe 01] - Criação das tabelas conforme a tarefa de descrição de requisitos (Edivaldo) 

### ISSUE THREAD

**Issue by FelipeOTSilva** [macielgoettms/ES2017#33]
Informar quais tabelas serão necessárias, informando nome dos campos, e tipos de cada um, para cada requisito abaixo:

 -> Lista de estilos disponivel 
 -> Comentário sobre evento.

**Comment by EdivaldoDalapria** [comment]
Criar a tabela: 'Estilo'

Com os seguintes campos:
idEstilos: INT, contém o código do estilo da cerveja.
nome: VARCHAR (40), contém o nome do estilo da cerveja.
descricricao:  VARCHAR (800), contém uma breve descrição.
comentario: VARCHAR (1000), opcional para os jurados escrever algum comentário.
