### ISSUE TITLE
 [Equipe 02] - Descrição de Requisito - Característica de estilo em evidência ao abrir o estilo (Cor,teor alcólico, Tipo de espuma) (Diayne) 

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#36]
Descrição dos seguintes requisitos:

- Característica de estilo em evidência ao abrir o estilo (Cor,teor alcólico, Tipo de espuma)

**Comment by Diayne** [comment]
- Característica de estilo em evidência ao abrir o estilo (Cor,teor alcoólico, Tipo de espuma): Em cada estilo de cerveja que o usuário selecionar, deverá ter como evidência, as principais características do estilo selecionado, que seria, a cor que a cerveja deve ter, o teor alcoólico, e o tipo de espuma;
