### ISSUE TITLE
[Equipe 02] - Diagrama

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#4]
Escolher qual ferramenta utilizar e qual diagrama irão desenvolver com a mesma.

**Comment by Luisczar15** [comment]
De acordo com pesquisas, serão utilizados os seguintes programas para criar os diagramas:

- Bizagi

- Astah

**Comment by frasnellicristian** [comment]
Oi Gabriel e Luis

**Comment by gabrielbenedet** [comment]
Abortado.
