### ISSUE TITLE
[Equipe 02] - Descrição do Requisito star rating de cada estilo de cerveja (Frasnelli)

### ISSUE THREAD

**Issue by gabrielbenedet** [macielgoettms/ES2017#41]
star rating de cada estilo de cerveja

**Comment by frasnellicristian** [comment]
Star rating de cada estilo de cerveja: O usuário depois de avaliar as cervejas artesanais através do aplicativo, terá que dar uma nota da cerveja provada, a forma de dar a nota é classificação por estrelas. Serão cinco estrelas, onde o usuário irá avaliar quantas estrelas merece a cerveja que ele provou, considerando seus conhecimentos em cervejas artesanais é claro.
